# title: Machine learning and other things
# author: GitHub User
# email: your-email@domain.com
# description: > # this means to ignore newlines until "show_exerpts:"
#   about Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# show_excerpts: true # set to true to show excerpts on the homepage
#
# # Minima date format
# # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
# sass:
#   sass_dir: _sass
#
# plainwhite:
#   name: Amir Sharifi
#   tagline: "Data Scientist."
#   date_format: "%b %-d, %Y"
#   sitemap: true # set to true to generate sitemap.xml content
#
#   # generate social links in footer
#   social_links:
#     twitter: Amirrrreza
#     github:  Coolsciguy
#     linkedIn: in/amir-sharifi-ph-d-4006ab46/
#
#
#     #rss: rss
#     # dribbble: jekyll
#     # facebook: jekyll
#     # flickr:   jekyll
#     # instagram: jekyll
#     # linkedin: jekyll
#     # pinterest: jekyll
#     # youtube: jekyll
#     # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
#     # youtube_channel_name: CloudCannon
#     # telegram: jekyll
#     # googleplus: +jekyll
#     # microdotblog: jekyll
#
#     # Mastodon instances
#     # mastodon:
#     # - username: jekyll
#     #   instance: example.com
#     # - username: jekyll2
#     #   instance: example.com
#
#
#   # navigation:
#   #   - title: My Work
#   #     url: "/my-work"
#   #   - title: about
#   #     url: "/about"
#
#
# # If you want to link only specific pages in your header, uncomment
# # this and add the path to the pages in order as they should show up
# #header_pages:
# # - about.md
#
#
#
# plugins:
#   - jekyll-seo-tag
# #  - jekyll-feed
#
#
# #Amir added this
# remote_theme: thelehhman/plainwhite-jekyll









title: Kushal's Technical Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Kushal's Projects and Experience
permalink: ':title/'

# Author Settings
author: Kushal Jaligama # add your name
author-img: kushal-jaligama.jpg # add your photo
about-author: Software Engineer, Roboticist, Interested in Human Cognition and AI, Long Distance Runner # add description
about-university: University of Michigan, Ann Arbor => Sep 2015 - Dec 2019
about-majors: Computer Science and Cognitive Science
about-internships: Previous Intern at Magna International, SpaceX, Tesla
about-skills: C/C++, Python, PID Control Systems, SIL/HIL, Validation, Continuous Integration, Computer Vision, Robotics, TensorFlow, Pytorch
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: kushalj1997 # add your Github handle
social-linkedin: kushal-jaligama-0b305a70/ # add your Linkedin handle
social-email: kjaligusa@gmail.com
social-soundcloud: https://soundcloud.com/kushal-jaligama/
social-audiomack: https://audiomack.com/artist/jollygama

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
